#!/usr/bin/env bash
set -e
case "$1" in
"nethack")
    ADD='-u https://nethackwiki.com'
    ;;
"cataclysm")
    ADD='-u http://cddawiki.chezzo.com -a cdda_wiki/api.php'
    ;;
*)
    ;;
esac
# this was in -E before tmux
TERM=xterm-256color
tmux popup -w 83 -E "tmux save-buffer - | xargs -I{} ~/.normen/bin/wikigrab -w 80 $ADD {} | less -R"
