#!/bin/bash
#tmux save-buffer -|ssh -x normenhansen@Normens-MacBook.local -i ~/.ssh/id_rsa -C 'pbcopy'
set -eu
# catch exceptions and display error message in tmux
trap 'tmux display-message "Error on line $LINENO: $BASH_COMMAND"' ERR
buf=$( tmux save-buffer - )
buflen=$( printf %s "$buf" | wc -c )
# 1MB limit
maxlen=1048576
if [ "$buflen" -gt "$maxlen" ]; then
  tmux display-message "input is %d bytes too long" "$(( buflen - maxlen ))" >&2
fi
esc="\033]52;c;$( printf %s "$buf" | head -c $maxlen | base64 | tr -d '\r\n' )\a"
esc="\033Ptmux;\033$esc\033\\"
pane_active_tty=$(tmux list-panes -F "#{pane_active} #{pane_tty}" | awk '$1=="1" { print $2 }')
printf "$esc" > "$pane_active_tty"
tmux display-message "Copied to system clipboard"
