#!/usr/bin/env bash
set -e

echo "**************************************************************"
echo ""
echo "🏠 install base apps (git,zsh,vim,ctags,vifm,mosh,tmux)?"
echo ""
select yn in "No" "Debian" "MacOS (install brew)" "MacOS (brew installed)";
do
  case $yn in
    "MacOS (install brew)" )
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      brew install vim ctags vifm mosh tmux
      break;;
    "MacOS (brew installed)" )
      brew install vim ctags vifm mosh tmux
      break;;
    "Debian" )
      sudo apt update
      sudo apt install git zsh vim ctags vifm mosh tmux
      chsh -s $(which zsh)
      sudo chsh -s $(which zsh) || true
      break;;
    "No" ) 
      break;;
  esac
done

cd ~/
if [ ! -d ".normen" ]; then
  git clone https://github.com/normen/.normen
fi

echo "**************************************************************"
echo ""
echo "📝 install vim plugins?"
echo ""
select yn in "No" "Yes" "Delete";
do
  case $yn in
    "Delete" )
      rm -rf ~/.normen/.vim/pack || true
      echo "all plugins deleted."
      ;;
    "Yes" )
      # gruvbox - eye candy
      git clone https://github.com/morhetz/gruvbox.git ~/.normen/.vim/pack/default/start/gruvbox || true
      # gitgutter - git infos in file
      git clone https://github.com/airblade/vim-gitgutter.git ~/.normen/.vim/pack/airblade/start/vim-gitgutter || true
      vim -u NONE -c "helptags ~/.normen/.vim/pack/airblade/start/vim-gitgutter/doc" -c q || true
      # fugitive - :G git command
      git clone https://tpope.io/vim/fugitive.git ~/.normen/.vim/pack/tpope/start/fugitive || true
      vim -u NONE -c "helptags ~/.normen/.vim/pack/tpope/start/fugitive/doc" -c q || true
      # surround - work on surrounding quotes etc
      git clone https://tpope.io/vim/surround.git ~/.normen/.vim/pack/tpope/start/surround || true
      vim -u NONE -c "helptags ~/.normen/.vim/pack/tpope/start/surround/doc" -c q || true
      # tbone - :Twrite / :Tyank etc. to work with tmux
      git clone https://tpope.io/vim/tbone.git ~/.normen/.vim/pack/tpope/start/tbone || true
      vim -u NONE -c "helptags ~/.normen/.vim/pack/tpope/start/tbone/doc" -c q || true
      # airline - bottom status line
      git clone https://github.com/vim-airline/vim-airline ~/.normen/.vim/pack/dist/start/vim-airline || true
      vim -u NONE -c "helptags ~/.normen/.vim/pack/dist/start/vim-airline/doc" -c q || true
      # vifm - integration with vifm file manager
      git clone https://github.com/vifm/vifm.vim ~/.normen/.vim/pack/default/start/vifm || true
      vim -u NONE -c "helptags ~/.normen/.vim/pack/default/start/vifm/doc" -c q || true
      # vimwiki - note taking
      git clone https://github.com/vimwiki/vimwiki ~/.normen/.vim/pack/default/start/vim-wiki || true
      vim -u NONE -c "helptags ~/.normen/.vim/pack/default/start/vim-wiki/doc" -c q || true
      # tmux-navigator - Ctrl-hjkl moving in tmux and vim
      git clone https://github.com/christoomey/vim-tmux-navigator.git ~/.normen/.vim/pack/default/start/vim-tmux-navigator || true
      vim -u NONE -c "helptags ~/.normen/.vim/pack/default/start/vim-tmux-navigator/doc" -c q || true
      # tmux-clipboard - auto-sync clipboard of tmux and vim
      git clone https://github.com/tmux-plugins/vim-tmux-focus-events ~/.normen/.vim/pack/default/start/vim-tmux-focus-events || true
      git clone https://github.com/roxma/vim-tmux-clipboard ~/.normen/.vim/pack/default/start/vim-tmux-clipboard || true
      vim -u NONE -c "helptags ~/.normen/.vim/pack/default/start/vim-tmux-clipboard/doc" -c q || true
      # tmux-resurrect tmux plugin
      git clone https://github.com/tmux-plugins/tmux-resurrect ~/.normen/.tmux/plugins/tmux-resurrect || true
      break;;
    "No" ) 
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "🚛 setup vifm?"
echo ""
echo "->do 'zo' in vifm then ':q'"
select yn in "No" "Yes";
do
  case $yn in
    "Yes" )
      vifm
      VIFM_PATH=~/.config/vifm
      if [ -d ~/.vifm ]; then
        VIFM_PATH=~/.vifm
      fi
      rm -rf $VIFM_PATH/colors
      git clone https://github.com/vifm/vifm-colors $VIFM_PATH/colors
      if grep -q "colorscheme gruvbox" "$VIFM_PATH/vifmrc"; then
        echo "Config already applied"
      else
        echo "colorscheme gruvbox">> $VIFM_PATH/vifmrc
        echo "nnoremap <C-e> :q<CR>">> $VIFM_PATH/vifmrc
      fi
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "📫 install aerc?"
echo ""
select yn in "No" "MacOS";
do
  case $yn in
    "MacOS" )
      brew install go scdoc jp2a imagemagick poppler catimg w3m dante keith/formulae/contacts-cli
      cd ~
      if [ ! -d ".normen/build/aerc" ]; then
        git clone https://git.sr.ht/~sircmpwn/aerc ~/.normen/build/aerc || true
      else
        cd ~/.normen/build/aerc
        make clean
        git pull --rebase
      fi
      cd ~/.normen/build/aerc
      make
      make install
      rm -rf ~/Library/Preferences/aerc || true
      ln -s ~/.normen/aerc ~/Library/Preferences/aerc
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "📦 install node 10?"
echo ""
select yn in "No" "sudo (n)" "nosudo (n)" "MacOS (brew)";
do
  case $yn in
    "sudo (n)" )
      cd ~/
      curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
      sudo bash n 10
      break;;
    "nosudo (n)" )
      cd ~/
      curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
      bash n 10
      break;;
    "MacOS (brew)" )
      brew install node@10
      brew link node@10 --force
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "😵 (📦) install YouCompleteMe?"
echo ""
select yn in "No" "Yes" "Delete";
do
  case $yn in
    "Delete" )
      rm -rf ~/.normen/.vim/pack/default/start/YouCompleteMe || true
      echo "YouCompleteMe deleted."
      ;;
    "Yes" )
      cd ~/.normen/.vim/pack/default/start
      git clone https://github.com/ycm-core/YouCompleteMe YouCompleteMe
      cd YouCompleteMe
      git submodule update --init --recursive
      python3 install.py --ts-completer
      break;;
    "No" ) 
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "🧐 (📦) install eslint + semistandard?"
echo ""
echo " -> mac usually nosudo"
select yn in "No" "sudo" "nosudo";
do
  case $yn in
    "nosudo" )
      npm install -g eslint semistandard
      break;;
    "sudo" )
      sudo npm install -g eslint semistandard --unsafe-perm
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "🚀 (📦) install spaceship?"
echo ""
echo " -> mac usually nosudo"
select yn in "No" "sudo" "nosudo";
do
  case $yn in
    "nosudo" )
      npm install -g spaceship-prompt
      break;;
    "sudo" )
      sudo npm install -g spaceship-prompt --unsafe-perm
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "🦶 replace / symlink dotfiles?"
echo ""
select yn in "No" "Yes";
do
  case $yn in
    "Yes" )
      rm -rf ~/.vim || true
      ln -s ~/.normen/.vim ~/.vim
      rm -f ~/.zshrc || true
      ln -s ~/.normen/.zshrc ~/.zshrc
      rm -f ~/.tmux || true
      ln -s ~/.normen/.tmux ~/.tmux
      rm -f ~/.tmux.conf || true
      ln -s ~/.normen/.tmux/tmux.conf ~/.tmux.conf
      rm -f ~/.inputrc || true
      ln -s ~/.normen/.inputrc ~/.inputrc
      rm -f ~/.eslintrc.json || true
      ln -s ~/.normen/.eslintrc.json ~/.eslintrc.json
      rm -f ~/.ctags || true
      ln -s ~/.normen/.ctags ~/.ctags
      break;;
    "No" )
      break;;
  esac
done

if [ -f ~/.normen/install.local ]; then
    ~/.normen/install.local
fi

