#!/usr/bin/env bash
set -e

echo "**************************************************************"
echo ""
echo "🏠 install base apps (git,zsh,vim,ctags,vifm,mosh,tmux)?"
echo ""
select yn in "No" "Debian" "MacOS (install brew)" "MacOS (brew installed)";
do
  case $yn in
    "MacOS (install brew)" )
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      brew install vim ctags vifm mosh tmux
      break;;
    "MacOS (brew installed)" )
      brew install vim ctags vifm mosh tmux
      break;;
    "Debian" )
      sudo apt update
      sudo apt install git zsh vim ctags vifm mosh tmux
      chsh -s $(which zsh)
      sudo chsh -s $(which zsh) || true
      break;;
    "No" ) 
      break;;
  esac
done

cd ~/
if [ ! -d ".normen" ]; then
  git clone https://github.com/normen/.normen
  # tmux-resurrect tmux plugin
  git clone https://github.com/tmux-plugins/tmux-resurrect ~/.normen/.tmux/plugins/tmux-resurrect || true
fi

echo "**************************************************************"
echo ""
echo "📝 install default plug.vim?"
echo ""
select yn in "No" "Yes" "Delete pack";
do
  case $yn in
    "Delete pack" )
      rm -rf ~/.normen/.vim/pack || true
      echo "all plugins in pack deleted"
      ;;
    "Yes" )
      cp ~/.normen/.vim/default_plug.vim ~/.normen/.vim/plug.vim
      # sneak - find with two characters
      #git clone https://github.com/justinmk/vim-sneak ~/.normen/.vim/pack/default/start/vim-sneak || true
      #vim -u NONE -c "helptags ~/.normen/.vim/pack/default/start/vim-sneak/doc" -c q || true
      break;;
    "No" ) 
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "🚛 setup vifm?"
echo ""
echo "->do 'zo' in vifm then ':q'"
select yn in "No" "Yes";
do
  case $yn in
    "Yes" )
      vifm
      VIFM_PATH=~/.config/vifm
      if [ -d ~/.vifm ]; then
        VIFM_PATH=~/.vifm
      fi
      rm -rf $VIFM_PATH/colors
      git clone https://github.com/vifm/vifm-colors $VIFM_PATH/colors
      if grep -q "colorscheme gruvbox" "$VIFM_PATH/vifmrc"; then
        echo "Config already applied"
      else
        echo "colorscheme gruvbox">> $VIFM_PATH/vifmrc
        echo "nnoremap <C-e> :q<CR>">> $VIFM_PATH/vifmrc
        echo "nmap ö :">> $VIFM_PATH/vifmrc
      fi
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "📫 install aerc?"
echo ""
select yn in "No" "MacOS";
do
  case $yn in
    "MacOS" )
      brew install go scdoc jp2a imagemagick poppler catimg w3m dante keith/formulae/contacts-cli
      cd ~
      if [ ! -d ".normen/build/aerc" ]; then
        git clone https://git.sr.ht/~sircmpwn/aerc ~/.normen/build/aerc || true
      else
        cd ~/.normen/build/aerc
        make clean
        git pull --rebase
      fi
      cd ~/.normen/build/aerc
      make
      make install
      rm -rf ~/Library/Preferences/aerc || true
      ln -s ~/.normen/aerc ~/Library/Preferences/aerc
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "📦 install node 10?"
echo ""
select yn in "No" "sudo (n)" "nosudo (n)" "MacOS (brew)";
do
  case $yn in
    "sudo (n)" )
      cd ~/
      curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
      sudo bash n 10
      break;;
    "nosudo (n)" )
      cd ~/
      curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
      bash n 10
      break;;
    "MacOS (brew)" )
      brew install node@10
      brew link node@10 --force
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "😵 (📦) install YouCompleteMe?"
echo ""
select yn in "No" "Yes" "Delete";
do
  case $yn in
    "Delete" )
      rm -rf ~/.normen/.vim/pack/default/start/YouCompleteMe || true
      echo "YouCompleteMe deleted."
      ;;
    "Yes" )
      cd ~/.normen/.vim/pack/default/start
      git clone https://github.com/ycm-core/YouCompleteMe YouCompleteMe
      cd YouCompleteMe
      git submodule update --init --recursive
      python3 install.py --ts-completer
      break;;
    "No" ) 
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "🧐 (📦) install eslint + semistandard?"
echo ""
echo " -> mac usually nosudo"
select yn in "No" "sudo" "nosudo";
do
  case $yn in
    "nosudo" )
      npm install -g eslint semistandard
      break;;
    "sudo" )
      sudo npm install -g eslint semistandard --unsafe-perm
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "🚀 (📦) install spaceship?"
echo ""
echo " -> mac usually nosudo"
select yn in "No" "sudo" "nosudo";
do
  case $yn in
    "nosudo" )
      npm install -g spaceship-prompt
      break;;
    "sudo" )
      sudo npm install -g spaceship-prompt --unsafe-perm
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo "🦶 replace / symlink dotfiles?"
echo ""
select yn in "No" "Yes";
do
  case $yn in
    "Yes" )
      rm -rf ~/.vim || true
      ln -s ~/.normen/.vim ~/.vim
      rm -f ~/.zshrc || true
      ln -s ~/.normen/.zshrc ~/.zshrc
      rm -f ~/.tmux || true
      ln -s ~/.normen/.tmux ~/.tmux
      rm -f ~/.tmux.conf || true
      ln -s ~/.normen/.tmux/tmux.conf ~/.tmux.conf
      rm -f ~/.inputrc || true
      ln -s ~/.normen/.inputrc ~/.inputrc
      rm -f ~/.eslintrc.json || true
      ln -s ~/.normen/.eslintrc.json ~/.eslintrc.json
      rm -f ~/.ctags || true
      ln -s ~/.normen/.ctags ~/.ctags
      rm -f ~/.nethackrc || true
      ln -s ~/.normen/.nethackrc ~/.nethackrc
      break;;
    "No" )
      break;;
  esac
done

if [ -f ~/.normen/install.local ]; then
    ~/.normen/install.local
fi

