#!/usr/bin/env bash
set -e

echo "**************************************************************"
echo ""
echo ".normen: install base apps (git,zsh,vim,ctags,vifm,mosh,tmux)?"
echo ""
select yn in "No" "Debian" "MacOS (install brew)" "MacOS (brew installed)";
do
  case $yn in
    "MacOS (install brew)" )
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      brew install vim ctags vifm mosh tmux
      break;;
    "MacOS (brew installed)" )
      brew install vim ctags vifm mosh tmux
      break;;
    "Debian" )
      sudo apt update
      sudo apt install git zsh vim ctags vifm mosh tmux
      chsh -s $(which zsh)
      sudo chsh -s $(which zsh) || true
      break;;
    "No" ) 
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo ".normen: install vim plugins?"
echo ""
select yn in "No" "Yes" "Delete";
do
  case $yn in
    "Delete" )
      rm -rf ~/.normen/.vim/pack || true
      echo "all plugins deleted."
      ;;
    "Yes" )
      git clone https://github.com/morhetz/gruvbox.git ~/.normen/.vim/pack/default/start/gruvbox
      git clone https://github.com/airblade/vim-gitgutter.git ~/.normen/.vim/pack/airblade/start/vim-gitgutter
      vim -u NONE -c "helptags ~/.normen/.vim/pack/airblade/start/vim-gitgutter/doc" -c q
      git clone https://tpope.io/vim/surround.git ~/.normen/.vim/pack/tpope/start/surround
      vim -u NONE -c "helptags ~/.normen/.vim/pack/tpope/start/surround/doc" -c q
      git clone https://github.com/vim-airline/vim-airline ~/.normen/.vim/pack/dist/start/vim-airline
      vim -u NONE -c "helptags ~/.normen/.vim/pack/dist/start/vim-airline/doc" -c q
      git clone https://github.com/vifm/vifm.vim ~/.normen/.vim/pack/default/start/vifm
      vim -u NONE -c "helptags ~/.normen/.vim/pack/default/start/vifm/doc" -c q
      git clone https://github.com/christoomey/vim-tmux-navigator.git ~/.normen/.vim/pack/default/start/vim-tmux-navigator
      vim -u NONE -c "helptags ~/.normen/.vim/pack/default/start/vim-tmux-navigator/doc" -c q
      break;;
    "No" ) 
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo ".normen: setup vifm? (do zo in vifm then :q)"
echo ""
select yn in "No" "Yes";
do
  case $yn in
    "Yes" )
      vifm
      rm -rf ~/.config/vifm/colors
      git clone https://github.com/vifm/vifm-colors ~/.config/vifm/colors
      echo "colorscheme gruvbox">> ~/.config/vifm/vifmrc
      echo "nnoremap <C-e> :q<CR>">> ~/.config/vifm/vifmrc
      break;;
    "No" )
      break;;
  esac
done


echo "**************************************************************"
echo ""
echo ".normen: install node 10?"
echo ""
select yn in "No" "sudo (n)" "nosudo (n)" "MacOS (brew)";
do
  case $yn in
    "sudo (n)" )
      cd ~/
      curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
      sudo bash n 10
      break;;
    "nosudo (n)" )
      cd ~/
      curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
      bash n 10
      break;;
    "MacOS (brew)" )
      brew install node@10
      brew link node@10 --force
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo ".normen: install eslint + semistandard?"
echo ""
echo " -> mac usually nosudo"
select yn in "No" "sudo" "nosudo";
do
  case $yn in
    "nosudo" )
      npm install -g eslint semistandard
      break;;
    "sudo" )
      sudo npm install -g eslint semistandard --unsafe-perm
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo ".normen: install spaceship?"
echo ""
echo " -> mac usually nosudo"
select yn in "No" "sudo" "nosudo";
do
  case $yn in
    "nosudo" )
      npm install -g spaceship-prompt
      break;;
    "sudo" )
      sudo npm install -g spaceship-prompt --unsafe-perm
      break;;
    "No" )
      break;;
  esac
done

echo "**************************************************************"
echo ""
echo ".normen: setup dotfiles?"
echo ""
select yn in "No" "Yes";
do
  case $yn in
    "Yes" )
      cd ~/
      if [ ! -d ".normen" ]; then
        git clone https://github.com/normen/.normen
      fi
      rm -rf ~/.vim || true
      ln -s ~/.normen/.vim ~/.vim
      rm -f ~/.zshrc || true
      ln -s ~/.normen/.zshrc ~/.zshrc
      rm -f ~/.tmux.conf || true
      ln -s ~/.normen/.tmux.conf ~/.tmux.conf
      rm -f ~/.inputrc || true
      ln -s ~/.normen/.inputrc ~/.inputrc
      rm -f ~/.eslintrc.json || true
      ln -s ~/.normen/.eslintrc.json ~/.eslintrc.json
      break;;
    "No" )
      break;;
  esac
done

