#!/bin/bash

echo ""
echo "⚡️*** tmux plugins ***"
if [ -d ~/.normen/.tmux/plugins/tpm ]; then
  ~/.normen/.tmux/plugins/tpm/bin/update_plugins all
fi

echo ""
echo "⚡️*** zsh plugins ***"
zsh -c 'source ~/.normen/.zshrc;antigen update'

echo ""
echo "⚡️*** vim plugins ***"
vim +PlugUpdate +qa

if [ -f ~/.normen/plugin-update.local ]; then
  ~/.normen/plugin-update.local
fi

