#!/bin/bash

if [ -d ~/.normen/.vim/pack ]; then
  ~/.normen/bin/git-recursive-update ~/.normen/.vim/pack
fi
if [ -d ~/.normen/.tmux/plugins ]; then
  ~/.normen/bin/git-recursive-update ~/.normen/.tmux/plugins
fi

echo "🤓 (node) update spaceship?"
echo " -> mac usually nosudo"
select yn in "No" "sudo" "nosudo";
do
  case $yn in
    "nosudo" )
      npm update -g spaceship-prompt
      break;;
    "sudo" )
      sudo npm update -g spaceship-prompt --unsafe-perm
      break;;
    "No" )
      break;;
  esac
done

echo "🤓 update YouCompleteMe?"
select yn in "No" "Yes";
do
  case $yn in
    "Yes" )
      cd ~/.vim/pack/default/start/YouCompleteMe
      git submodule update --init --recursive
      python3 install.py --ts-completer
      break;;
    "No" )
      break;;
  esac
done

if [ -f ~/.normen/plugin-update.local ]; then
  ~/.normen/plugin-update.local
fi

