#!/bin/bash

if [ -d ~/.normen/.tmux/plugins ]; then
  ~/.normen/bin/git-recursive-update ~/.normen/.tmux/plugins
fi

zsh -c 'source ~/.normen/.zshrc;antigen update'

vim +CocUpdateSync +PlugUpdate +qa

if [ -f ~/.normen/plugin-update.local ]; then
  ~/.normen/plugin-update.local
fi

