" standard stuff
set nocompatible
set noswapfile
set encoding=utf-8
syntax enable
filetype plugin indent on
color default
colorscheme gruvbox
set background=dark
set splitbelow splitright
set number
set relativenumber
set ruler
set showcmd
set tabstop=2
set shiftwidth=2
set expandtab
set nowrap
set linebreak
set cursorline
" avoid adding line breaks while typing
set textwidth=0
set noerrorbells
"set display=truncate
set updatetime=500
set mouse=a
set ttymouse=xterm2
"set clipboard=unnamed
set path+=**
set wildmenu
set wildignore=*.o,*.obj,*-
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*node_modules*
set wildignore+=*DS_Store*
set wildignore+=*.png,*.jpg*,*.gif
" let backspace delete eol, before insert etc.
set backspace=2

set autoread
set autoindent
set smartindent

" interactive search
set hls is
" ignore case
set ic

" Lexplore NerdierTree
let g:netrw_banner = 0
let g:netrw_liststyle = 3
" open in previous window
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25
" vertical split
let g:netrw_preview = 1

" nicer vsplit character
set fillchars+=vert:\┃

" avoid issues with tmux and color schemes
set t_Co=256
" disable Background Color Erase (BCE) so that color schemes
" render properly when inside 256-color tmux and GNU screen.
" see also http://snk.tuxfamily.org/log/vim-256color-bce.html
if &term =~ '256color'
  set t_ut=
endif

" MacOS Terminal path in title
" use Ctrl-V Esc and Ctrl-V Ctrl-G to insert
set t_ts=]6;
set t_fs=
set title
"set titlestring=%{\"file://\".hostname().expand(\"%:p\")}
auto BufEnter * let &titlestring = "file://" . substitute(hostname().expand("%:p"), " ", "+", "")

" set vimwiki path and syntax
let g:vimwiki_list = [{'path': '~/.normen/vimwiki/', 'syntax': 'markdown', 'ext': '.md', "nested_syntaxes": {'javascript':'javascript','bash':'bash','sh':'sh','c++':'cpp','python':'python'}}]
let g:vimwiki_markdown_link_ext = 1
let g:vimwiki_global_ext = 0

" disable gitgutter if no git executable
if !executable('git')
  let g:gitgutter_enabled = 0
endif

" allow toggling quick fix window
function! QuickFix_toggle()
  for i in range(1, winnr('$'))
    let bnum = winbufnr(i)
    if getbufvar(bnum, '&buftype') == 'quickfix'
      cclose
      return
    endif
  endfor
  copen
endfunction

" ** Mappings & Commands **
let mapleader = ","

" session / project setup
nnoremap <F1> :!~/.normen/update<CR><CR>
nnoremap <F2> :silent mksession! session.vim<CR>
nnoremap <F3> :!~/.normen/push<CR><CR>

" build/generate commands
nnoremap <F4> :silent set ft=homebridge\|make\|set ft=javascript<CR>
nnoremap <F5> :silent make<CR>:cw<CR><C-L>
nnoremap <F6> :silent !semistandard % --fix<CR><C-L>
nnoremap <F7> :silent !ctags -R .<CR><C-L>

nnoremap <F8> :silent call QuickFix_toggle()<CR>
nnoremap <F9> :cp<CR>
nnoremap <F10> :cn<CR>

" Toggle Lexplore or vifm with Ctrl-E
if !executable('vifm')
  map <silent> <C-E> :Lexplore<CR>
else
  map <silent> <C-E> :Vifm<CR>
  map <silent> <C-W><C-E> :VsplitVifm<CR>
endif

" window nav
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
noremap <silent> <C-Up> :resize +3<CR>
noremap <silent> <C-Down> :resize -3<CR>
noremap <silent> <C-Left> :vertical resize -3<CR>
noremap <silent> <C-Right> :vertical resize +3<CR>

"masochism
nnoremap <up> ddkP
vnoremap <up> dkP
nnoremap <down> ddjP
vnoremap <down> djp
nnoremap <left> O<Esc>j
nnoremap <right> o<Esc>k

" copy-paste easily from clipboard
nnoremap <Leader>yy "*yy
vnoremap <Leader>y "*y
nnoremap <Leader>p "*p
nnoremap <Leader>P "*P

" quick tools
nnoremap <Leader>n :noh<CR>
nnoremap <Leader>. @w

" wiki split
nmap <Leader>wv :50vsplit<CR>,ww

" opening/closing brackets
inoremap {<CR> {<CR>}<ESC>O

" german keys
nmap ü ]
nnoremap ]ü ]]
nmap ä [
nnoremap [ä [[

" operate on 'method'
nnoremap vm Vf{%
nnoremap dm Vf{%d
nnoremap ym Vf{%y
nnoremap cm Vf{%c

" operate on 'all method'
nnoremap vam va{V
nnoremap dam va{Vd
nnoremap yam va{Vy
nnoremap cam va{Vc

" commenting
map <Leader># :s/^/#/<CR>:noh<CR>
map <Leader>/ :s/^/\/\//<CR>:noh<CR>
map <Leader>" :s/^/\"/<CR>:noh<CR>
map <Leader>% :s/^/%/<CR>:noh<CR>
map <Leader>! :s/^/!/<CR>:noh<CR>
map <Leader>; :s/^/;/<CR>:noh<CR>
map <Leader>- :s/^/--/<CR>:noh<CR>
map <Leader><BS> :s/^\/\/\\|^--\\|^> \\|^[#"%!;]//<CR>:noh<CR>

"map <Leader>* :s/^\(.*\)$/\/\* \1 \*\//<CR>:noh<CR>
"map <Leader>( :s/^\(.*\)$/\(\* \1 \*\)/<CR>:noh<CR>
"map <Leader>< :s/^\(.*\)$/<!-- \1 -->/<CR>:noh<CR>
"map <Leader>d :s/^\([/(]\*\\|<!--\) \(.*\) \(\*[/)]\\|-->\)$/\2/<CR>:noh<CR>

" custom commands
:command W w

:command -nargs=* Search :vim /<args>/g %<bar>cw
:command -nargs=* SearchFiles :vim /<args>/g **/*<bar>cw
:command FixLineEndings :%s//\r/g
:command FixAdditionalLineEndings :%s///g
:command FormatJSON :%!python -m json.tool

":command -nargs=1 GitClone Git clone <args>
":command GitInit Git init
":command GitCommit Git commit
:command GitCommitThis Git add %|Git commit
:command GitCommitAll Git add -A|Git commit
:command GitPushMaster Git push -f -u origin master
":command GitPushAllMaster Git add -A|Git commit|Git push -f -u origin master
:command GitPullMaster Git pull --rebase origin master
:command GitStash Git stash save -a
:command GitPop Git stash pop
:command GitUntracked Git ls-files --others --exclude-standard
:command GitUnStageAll Git reset HEAD -- .

:command HbUploadPlugin !rsync -azrv --delete ${PWD} pi@homebridge.local:~/npm-code/
:command HbUploadPluginDry !rsync -n -azrv --delete ${PWD} pi@homebridge.local:~/npm-code/
:command HbDownloadPlugin !rsync -azrv --delete pi@homebridge.local:~/npm-code/${PWD\#\#*/} ~/Dev/NodeCode/homebridge/npm-code/
:command HbDownloadPluginDry !rsync -n -azrv --delete pi@homebridge.local:~/npm-code/${PWD\#\#*/} ~/Dev/NodeCode/homebridge/npm-code/
:command HbFullUpload !rsync -azrv --delete ~/Dev/NodeCode/homebridge/npm-code pi@homebridge.local:~/
:command HbFullUploadDry !rsync -n -azrv --delete ~/Dev/NodeCode/homebridge/npm-code pi@homebridge.local:~/
:command HbFullDownload !rsync -azrv --delete pi@homebridge.local:~/npm-code ~/Dev/NodeCode/homebridge/
:command HbFullDownloadDry !rsync -n -azrv --delete pi@homebridge.local:~/npm-code ~/Dev/NodeCode/homebridge/

:command BackupDev !rsync -azrv --delete ~/Dev normen@normenhansen.de:~/backup/MacBook
:command RestoreDevDry !rsync -n -azrv --delete normen@normenhansen.de:~/backup/MacBook/Dev ~/

:command WebAppUp !cd client;npm run build;cd ..;git add -A;git commit -m 'update';git push -u -f origin master

:command PIOCreateMakefile !cp ~/.vim/templates/PlatformIO-Makefile ./Makefile
:command -nargs=1 PIOInit !platformio project init --ide vim --board <args>

:command JSCompletionEnable !cp ~/.vim/templates/jsconfig.json ./

