#!/bin/sh
pandoc -f html -t plain
# aerc filter which runs w3m using socksify (from the dante package) to prevent
# any phoning home by rendered emails
#export SOCKS_SERVER="127.0.0.1:1"
#exec socksify w3m \
#  -T text/html \
#  -dump \
#  -o display_image=false \
#  -o display_link_number=true
#	-cols $(tput cols) \

